### ISSUE TITLE
will this system property script work after I create a JPackage ?

### ISSUE THREAD

**Issue by harideva16** [liblit/simple-jni#4]
https://github.com/liblit/simple-jni/blob/60f2cf9603121d843b1adcafbc34bf07a2c645c1/build.gradle#L26-L37

I want to craete a JPackage .

will this system property script work after I create a JPackage ?

**Comment by liblit** [comment]
I have no idea, as I'm not at all familiar with JPackage.

Also, please observe that the most recent commit to this repository was more than three years ago. Host platforms evolve, as does Gradle itself. The way things are set up in this repository may have been correct three years ago, but I doubt that I'd do it the same way today. I recommend that you look for more recent examples elsewhere.
