### ISSUE TITLE
will this project helps to bundle a native library and a JNI library inside a JAR?


### ISSUE THREAD

**Issue by ghost** [liblit/simple-jni#6]
I have a doubt .

I want to create a JAR with this project. 

will this project helps to bundle a native library and a JNI library inside a JAR?

**Comment by liblit** [comment]
> will this project helps to bundle a native library and a JNI library inside a JAR?

Unlikely. Nothing in this project addresses bundling of any kind.

Furthermore, as [I've told you before](https://github.com/liblit/simple-jni/issues/1#issuecomment-898942398), the most recent commit to this repository was more than three years ago. Host platforms evolve, as does Gradle itself. The way things are set up in this repository may have been correct three years ago, but I doubt that I'd do it the same way today. **I recommend that you look for more recent examples elsewhere.**
